services:
  jira:
    image: atlassian/jira-software:10.0.0
    container_name: jira
    user: root
    ports:
      - "8080:8080"
    volumes:
      - /opt/jira/jira/data:/var/atlassian/application-data/jira
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/jiradb
      - ATL_JDBC_USER=sypchik
      - ATL_JDBC_PASSWORD=qwertyui
      - ATL_DB_TYPE=postgres72

  db:
    image: postgres:15
    container_name: jira-db
    restart: always
    user: root
    environment:
      POSTGRES_USER: sypchik
      POSTGRES_PASSWORD: qwertyui
      POSTGRES_DB: jiradb
    volumes:
      - /opt/jira/postgres/data:/var/lib/postgresql/data
